/// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
/// By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
/// find the sum of the even-valued terms.*/
/*

                                        BRAINSTORM YOURSELF FIRST

*/
#include <iostream>         /// iostream header file
using namespace std;        /// adding the namespace std;
int main()                  /// main() function with int data type
{
    int next_num = 2 ,pre_num = 1;      /// declaring & initializing of next number = 2 and previous number = 1.
                                        /// we have started with 2 + 1 thats why the next num is 2 & pre_num is 1.
    int ans_num=0;                      /// ans_num is used to store the sum of next_num and pre_num.
    int total=0;                        /// total is a int variable which will be used to store the sum of all even-valued terms less the 4000000
    while (ans_num<4000000)             /// iteration will happen till the last term should be less than 4 million
    {
        if(next_num%2==0)               /// this will check the term is even or not
        {
            total = total + next_num;   /// if the term is even then adding that term with previously added terms
        }                               /// here total will add & store the even-valued fibonacci terms
        ans_num = next_num + pre_num;   /// this is the main recursive algorithm which adds the next & previous number
                                        /// here we changed the values to make our algorithm act recursively
        pre_num = next_num;             /// now we have changed the previous number value to next_number
        next_num = ans_num;             /// and making the next_number value to new calculated ans_number value
        cout << ans_num << endl;        /// just for outputting the current calculated output 'and_num';
    }
    if(ans_num>4000000)                 /// if the ans_num current value is greater than 4 million
        {
            ans_num = ans_num - pre_num;    /// then make the current ans_num less than 4 million
        }
    cout << "last ans_num value: " << ans_num << "\n";      /// outputting the current calculated ans_num
    cout << "The sum of the even-valued terms of fibonacci sequence <4000000: " << total << endl; /// outputting the main answer for our question
    return 0;           /// returning the 0 for showing we have succeded
}
